# Generated by Django 4.2.4 on 2023-08-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_veiculo_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
    ]
