# Generated by Django 4.2.1 on 2023-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório'},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo'},
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
