# Generated by Django 4.2.4 on 2023-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem', '0006_remove_veiculo_imagem_veiculo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='imagem',
            field=models.ManyToManyField(related_name='+', to='uploader.image'),
        ),
    ]
